### ISSUE TITLE
Change password/hash

### ISSUE THREAD

**Issue by schoena** [CincyPy/LibraryWebsite#57]
-Allow people to change their password (without Admin doing it)
- hash the passwords

**Comment by hitbox** [comment]
I'll take this if no one else wants it.

**Comment by hitbox** [comment]
Hold off on merging, I'll make it so that it will verify against their current password scheme and change it over.

**Comment by hitbox** [comment]
[Updated pull request](https://github.com/CincyPy/LibraryWebsite/pull/59)

**Comment by Stamates** [comment]
Merged Carl's pull request resolving this issue
